name: Consortium for the Improvement in Quality and Productivity in Clinical Research2
favicon: null
layout_spectrum: 0.0411299760453403
typography_spectrum: 0.5246587379369885
title: Consortium for the Improvement in Quality and Productivity in Clinical Research
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2139'
    - '#ff0000'
    - '#95909c'
    - '#ff8c00'
    - '#fdfdfd'
  brandStrength: 0.5
  lightness: 0.427032764069736
  saturation: 0.18966340366750956
  rhythmicContrast: 0.6207313113845885
purpose: []
